app:
  name: syt-go-queue
  mode: development
  port: 8080

redis:
  addr: localhost:6390
  password: ""
  db: 0

mysql:
  dsn: root:password@tcp(localhost:3306)/syt_queue?charset=utf8mb4&parseTime=True&loc=Local
  max_idle_conns: 10
  max_open_conns: 100

deepseek:
  api_key: your_api_key
  base_url: https://api.deepseek.com/v1
  timeout: 30s
  model: deepseek-chat
  max_tokens: 2000
  circuit_breaker:
    enabled: true
    max_requests: 2
    interval: 1m
    timeout: 2m
    fail_threshold: 0.5

queue:
  concurrency: 10
  retry: 3
  retention: 24h

logger:
  level: info
  development: true

auth:
  enabled: true
  realm: "SYT Go Queue API"
  users:
    admin: admin123
    api: api123